# Generated by Django 5.2.7 on 2025-10-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_form_feedback_filled_by_alter_videos_uploader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_link',
            field=models.CharField(max_length=1024),
        ),
    ]
