# Generated by Django 5.2.7 on 2025-10-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_videos_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video_link',
            new_name='video_url',
        ),
    ]
