# Generated by Django 5.2.7 on 2025-10-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_rename_video_link_videos_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_feedback',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
