# Generated by Django 5.2.7 on 2025-10-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_form_feedback_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
