# Generated by Django 5.2.7 on 2025-10-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_videos_school_name'),
        ('feedback', '0008_create_superuser'),
    ]

    operations = [
    ]
